# Generated by Django 4.2.17 on 2026-04-07 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_item_goodsreceived_goodsissue_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockledger',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('RETURN', 'Stock Return')], max_length=10),
        ),
        migrations.CreateModel(
            name='GoodsReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(help_text='Reason for return')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_returns', to='api.item')),
                ('original_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='api.goodsissue')),
                ('returned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Goods Return',
                'verbose_name_plural': 'Goods Returns',
                'db_table': 'goods_return',
                'ordering': ['-return_date'],
            },
        ),
    ]
